### ISSUE TITLE
Manually invoke rehydration?

### ISSUE THREAD

**Issue by ekrapfl** [Michsior14/ngrx-addons#198]
I have another complex `APP_INITIALIZER` and rehydration issue for you.

[Reproduction code](https://stackblitz.com/edit/angular-ivy-uhttnp?file=src%2Fapp%2Fapp.module.ts)

I think where I am is that I want to be able to manually invoke rehydration when I want it to happen, and I want to be able to await it.

The reasoning for this is that I have some async code that I need to happen before rehydration, and then I also have factory providers that I want to use a bit of state from the store (but that has to happen after rehydration).  The best way I can think to do that is to manually tell the plugin when to rehydrate, and to make sure it is awaited, all in my `APP_INITIALIZER`.

In the example, I am sort of doing what I am suggesting, but it also requires a bit of a hack in the `storage` handler to make sure rehydrate gets fired even when there is nothing in the database.  That is definitely not ideal.  It could be handled with a different action `RehydrationFinished` or something like that, as well.

Is that making sense what I am asking for?  And do you have some better way to do it?

**Comment by ekrapfl** [comment]
Just to clarify, I think what I am asking for is this:
A `ManualRehydration` strategy.

I imagine something like this:
```ts
PersistStateModule.forRoot({ states: [], strategy: ManualRehydration })
```

And then in my `APP_INITIALIZER`, I would do something like so:
```ts
(manualRehydrationStrategy: ManualRehydration) => async () => {
  // Do some asynchronous stuff
  
  // Manually invoke and await rehydration of the store here
  await manualRehydrationStrategy.rehydrate();
}
```

**Comment by Michsior14** [comment]
The custom strategy is what I initially thought you can use. It's as easy as implementing `InitializationStrategy` interface, the problem is the awaiting part, I am just using `dispatch` to fire `rehydrate` action and don't feel comfortable to provide way to wait for it for the same reason why `dispatch` can't be awaited. You could probably mitigate it in custom strategy by checking actions as you did in the example. Does it help?

**Comment by ekrapfl** [comment]
I don't mind that idea for the most part.  The trick is figuring out when all of the pieces have been rehydrated.  That is fairly complicated, I think.  Unless, perhaps, I am missing something.  How would I determine that _everything_ has been rehydrated?

**Comment by ekrapfl** [comment]
I think it would help a lot if there was an action specifically for when all of the rehydration has completed.  Something like `@ngrx-addons/persist-state/rehydration-complete`

**Comment by Michsior14** [comment]
The problem with the `complete` action is that the lib won't have an idea when it happens too, due `feature states` (i.e. in lazy loaded modules) that won't be available directly on the app start.

Since you should know all the feature/root states it's should be possible to do something like [this](https://stackblitz.com/edit/angular-ivy-dm2qgp?file=src%2Fapp%2Fapp.module.ts).

**Comment by ekrapfl** [comment]
That's fairly doable.  What about situations where the rehydrate action is never called because there was nothing in the DB?  I felt like checking for that in the storage strategy and returning an object was a bit hacky.

**Comment by Michsior14** [comment]
Right, this an problem indeed. I am skipping null values because otherwise initial state is overwritten. Not sure how to tackle this inside the lib. I could provide option to skip filtering, would it be enough (could create some unwanted side effects)? Other option would be to utilize `debounceTime` or check if all required keys has been requested from storage.

**Comment by ekrapfl** [comment]
I think you've given me enough ideas to work with here.  And I totally get why you can't implement the `completed` action like I was suggesting.  I think I can work around it myself, since I know the keys that I care to have rehydrated.  Thanks for the input!  I will close out the issue.
